/obj/item/mech_component/propulsion/heavy
	name = "heavy legs"
	desc = "Oversized actuators struggle to move these armoured legs. "
	exosuit_desc_string = "heavy hydraulic legs"
	icon_state = "heavy_legs"
	mech_turn_sound = 'sound/mecha/mechmove01.ogg'
	mech_step_sound = 'sound/mecha/mechstep03.ogg'
	move_delay = 5
	turn_delay = 5
	power_use = 100
	max_damage = 500
	min_damage = 300
	max_repair = 150
	repair_damage = 20
	bump_type = HARD_BUMP
	bump_safety = FALSE
	req_material = MATERIAL_PLASTEEL
	back_modificator_damage = 4
	front_modificator_damage = 0.5
	max_heat = 300
	heat_cooling = 4
	emp_heat_generation = 100
	heat_generation = 5
	max_speed = 4.5
	min_speed = 8
	acceleration = 1
	turn_slowdown = 2
	turn_diogonal_slowdown = 1.5
	weight = 400
