/obj/item/mech_component/propulsion/powerloader
	name = "exosuit legs"
	desc = "Wide and stable but not particularly fast."
	exosuit_desc_string = "reinforced hydraulic legs"
	mech_step_sound = 'sound/mecha/mechstep03.ogg'
	move_delay = 4
	turn_delay = 4
	power_use = 10
	max_damage = 100
	min_damage = 50
	max_repair = 30
	repair_damage = 10
	bump_type = MEDIUM_BUMP
	back_modificator_damage = 1.3
	front_modificator_damage = 1
	max_heat = 100
	heat_cooling = 7
	emp_heat_generation = 50
	heat_generation = 2
	max_speed = 4
	min_speed = 6
	acceleration = 0.75
	turn_slowdown = 1.25
	turn_diogonal_slowdown = 1.75
	weight = 150
