/obj/item/mech_component/manipulators/heavy
	name = "heavy arms"
	desc = "Designed to function where any other piece of equipment would have long fallen apart, the Hephaestus Superheavy Lifter series can take a beating and excel at delivering it."
	exosuit_desc_string = "super-heavy reinforced manipulators"
	icon_state = "heavy_arms"
	punch_sound = 'sound/mecha/mech_punch_slow.ogg'
	action_delay = 20
	power_use = 60
	melee_damage = 40
	max_repair = 150
	max_damage = 500
	min_damage = 300
	repair_damage = 30
	req_material = MATERIAL_PLASTEEL
	back_modificator_damage = 4
	front_modificator_damage = 0.5
	max_heat = 300
	heat_cooling = 4
	emp_heat_generation = 100
	heat_generation = 15
	weight = 400
