/obj/item/mech_component/manipulators/powerloader
	name = "exosuit arms"
	desc = "The Xion Industrial Digital Interaction Manifolds allow you poke untold dangers from the relative safety of your cockpit."
	exosuit_desc_string = "heavy-duty industrial lifters"
	punch_sound = 'sound/mecha/mech_punch_slow.ogg'
	max_damage = 100
	min_damage = 50
	power_use = 30
	min_damage = 50
	max_repair = 30
	melee_damage = 30
	repair_damage = 10
	back_modificator_damage = 1.3
	front_modificator_damage = 1
	max_heat = 100
	heat_cooling = 7
	emp_heat_generation = 75
	heat_generation = 5
	weight = 150
