#define DONATION_TIER_NONE   FLAG(0)
#define DONATION_TIER_ONE    FLAG(1)
#define DONATION_TIER_TWO    FLAG(2)
#define DONATION_TIER_THREE  FLAG(3)
#define DONATION_TIER_FOUR   FLAG(4)

#define DONATION_TIER_ALL_TIERS list(\
	DONATION_TIER_NONE, DONATION_TIER_ONE, \
	DONATION_TIER_TWO, DONATION_TIER_THREE, \
	DONATION_TIER_FOUR)

#define DONATIONS_TRANSACTION_TYPE_PURCHASE "loadout_item_purchase"
