// MUST BE IN SYNC WITH DB
#define DONATION_TIER_NONE   "none"
#define DONATION_TIER_ONE    "Tier 1"
#define DONATION_TIER_TWO    "Tier 2"
#define DONATION_TIER_THREE  "Tier 3"
#define DONATION_TIER_FOUR   "Tier 4"

#define DONATIONS_TRANSACTION_TYPE_PURCHASE "loadout_item_purchase"

#define DONATION_TIER_ALL_TIERS list(\
	DONATION_TIER_NONE, DONATION_TIER_ONE, \
	DONATION_TIER_TWO, DONATION_TIER_THREE, \
	DONATION_TIER_FOUR)
