/datum/trading_station/civilian
	name_pool = list(
		"FTB \"Wardrobe\"" = "Free Trade Beacon \"Wardrobe\": leisure goods, uniforms, and non-essential comforts.",
		"FTB \"Bazaar\"" = "Free Trade Beacon \"Bazaar\": merchant goods, passenger clothing, and civilian trade items.",
		"FTB \"Comfort Line\"" = "Free Trade Beacon \"Comfort Line\": off-duty apparel, comfort accessories, and leisure supplies.",
		"FTB \"Mercantile\"" = "Free Trade Beacon \"Mercantile\": recreational wares, uniform replacements, and general civilian comforts."
	)
	uid = "civilian"
	icon_states = list("trade")
	unlock_favor = 2500
	faction = FACTION_INDEPENDENT
	spawn_always = TRUE
	markup = 1.2
	thematic_cores = list("Mess Hall", "Wardrobe", "Pantry Post", "Cornucopia", "Hydro-Haven", "Bazaar", "Comfort Line", "Mercantile", "Haven")
	role_summary = "crew provisions, leisure goods, commissary wares, and textiles"
	inventory = list(
		TRADE_CAT_CLOTHING = list(
			/obj/item/clothing/under/color/blackjumpshorts = GOODS_DEFAULT,
			/obj/item/clothing/under/rank/roboticist/skirt = GOODS_DEFAULT,
			/obj/item/clothing/under/sl_suit = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/burgundy = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/charcoal = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/checkered = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/really_black = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/female = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/navy = GOODS_DEFAULT,
			/obj/item/clothing/under/lawyer/oldman = GOODS_DEFAULT,
			/obj/item/clothing/under/lawyer/purpsuit = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/red = GOODS_DEFAULT,
			/obj/item/clothing/under/lawyer/blue = GOODS_DEFAULT,
			/obj/item/clothing/under/gentlesuit = GOODS_DEFAULT,
			/obj/item/clothing/under/lawyer/black = GOODS_DEFAULT,
			/obj/item/clothing/under/suit_jacket/tan = GOODS_DEFAULT,
			/obj/item/clothing/under/scratch = GOODS_DEFAULT,
			/obj/item/clothing/under/lawyer/bluesuit = GOODS_DEFAULT,
			/obj/item/clothing/under/rank/internalaffairs/plain = GOODS_DEFAULT,
			/obj/item/clothing/under/blazer = GOODS_DEFAULT,
			/obj/item/clothing/under/blackjumpskirt = GOODS_DEFAULT,
			/obj/item/clothing/under/kilt = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_hr = GOODS_DEFAULT,
			/obj/item/clothing/under/det = GOODS_DEFAULT,
			/obj/item/clothing/under/det/black = GOODS_DEFAULT,
			/obj/item/clothing/under/det/grey = GOODS_DEFAULT,
			/obj/item/clothing/under/sundress_white = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_fire = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_green = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_orange = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_pink = GOODS_DEFAULT,
			/obj/item/clothing/under/dress/dress_purple = GOODS_DEFAULT,
			/obj/item/clothing/under/sundress = GOODS_DEFAULT,
			/obj/item/clothing/under/rank/scientist/zeng = GOODS_DEFAULT,
			/obj/item/clothing/under/mbill = GOODS_DEFAULT,
			/obj/item/clothing/under/saare = GOODS_DEFAULT,
			/obj/item/clothing/under/aether = GOODS_DEFAULT,
			/obj/item/clothing/under/hephaestus = GOODS_DEFAULT,
			/obj/item/clothing/under/pcrc = GOODS_DEFAULT,
			/obj/item/clothing/under/pcrcsuit = GOODS_DEFAULT,
			/obj/item/clothing/under/wardt = GOODS_DEFAULT,
			/obj/item/clothing/under/grayson = GOODS_DEFAULT,
			/obj/item/clothing/under/focal = GOODS_DEFAULT,
			/obj/item/clothing/under/rank/ntwork = GOODS_DEFAULT,
			/obj/item/clothing/under/morpheus = GOODS_DEFAULT,
			/obj/item/clothing/under/skinner = GOODS_DEFAULT,
			/obj/item/clothing/under/dais = GOODS_DEFAULT,
			/obj/item/clothing/under/rank/roboticist/bishop = GOODS_DEFAULT,
			/obj/item/clothing/under/hazard = GOODS_DEFAULT,
			/obj/item/clothing/under/frontier = GOODS_DEFAULT,
			/obj/item/clothing/under/redpyjamas = GOODS_DEFAULT,
			/obj/item/clothing/under/bluepyjamas = GOODS_DEFAULT
		),
		TRADE_CAT_LEISURE = list(
			/obj/item/instrument/guitar = GOODS_DEFAULT,
			/obj/item/device/synthesized_instrument/synthesizer = GOODS_DEFAULT,
			/obj/item/device/synthesized_instrument/guitar = GOODS_DEFAULT,
			/obj/item/device/synthesized_instrument/trumpet = GOODS_DEFAULT,
			/obj/item/pack/cardemon = GOODS_DEFAULT,
			/obj/item/deck/holder = GOODS_DEFAULT,
			/obj/item/deck/cards = GOODS_DEFAULT,
			/obj/item/storage/pill_bottle/dice = GOODS_DEFAULT,
			/obj/item/paper_bin = GOODS_DEFAULT,
			/obj/item/pen = GOODS_DEFAULT,
			/obj/item/pen/blue = GOODS_DEFAULT,
			/obj/item/pen/red = GOODS_DEFAULT,
			/obj/item/storage/fancy/crayons = GOODS_DEFAULT,
			/obj/item/device/camera = GOODS_DEFAULT,
			/obj/item/device/camera_film = GOODS_DEFAULT,
			/obj/item/storage/photo_album = GOODS_DEFAULT
		)
	)
