//Взаимодействие с мехом
#include "../code\mech_interaction\main_mech_interaction.dm"
#include "../code\mech_interaction\pilot.dm"
#include "../code\mech_interaction\just_interaction\emag_act.dm"
#include "../code\mech_interaction\just_interaction\id_card_interaction.dm"
#include "../code\mech_interaction\maint_interaction\coil_repair.dm"
#include "../code\mech_interaction\maint_interaction\customisation.dm"
#include "../code\mech_interaction\maint_interaction\deinstall_cell.dm"
#include "../code\mech_interaction\maint_interaction\deinstall_equipment.dm"
#include "../code\mech_interaction\maint_interaction\force_hatch.dm"
#include "../code\mech_interaction\maint_interaction\install_cell.dm"
#include "../code\mech_interaction\maint_interaction\install_equipment.dm"
#include "../code\mech_interaction\maint_interaction\start_dismantle_mech.dm"
#include "../code\mech_interaction\maint_interaction\welder_repair.dm"
#include "../code\mech_interaction\maint_interaction\material_repair.dm"
#include "../code\mech_interaction\maint_interaction\mech_bolts.dm"
#include "../code\mech_interaction\maint_interaction\paint.dm"
#include "../code\equipment\install_remove.dm"
