#ifndef MODPACK_IPC_MODS
#define MODPACK_IPC_MODS

#include "_ipc_mods.dm"
#include "code/cooling_system.dm"
#include "code/external_cooling_device.dm"
#include "code/machine.dm"
#include "code/exonet_connection_system.dm"
#include "code/dev_exonet_connection_system.dm"
#include "code/directive_disk.dm"
#include "code/ipc.dm"
#include "code/items.dm"
#include "code/machine_functions.dm"
#include "code/handle_enviroment.dm"
#include "code/pictures.dm"
#include "code/coolerbelt.dm"
#include "code/prosthetics.dm"
#include "code/roborepair.dm"
#include "code/robosurgery.dm"
#include "code/cargo.dm"
#include "code/accessory_ipc.dm"
#include "code/diagnostics.dm"
#include "code/power_reroute.dm"
#include "code/rig_adapter.dm"
#endif
