/mob/living/exosuit/proc/turn_mech(moving_dir)
	do_mech_step_sound()
	if(dir == turn(dir, 45) || dir == turn(dir, -45))
		sub_speed(L_leg.turn_diogonal_slowdown)
		sub_speed(R_leg.turn_diogonal_slowdown)
	else if(dir == turn(dir, 90) || dir == turn(dir, -90))
		sub_speed(L_leg.turn_slowdown )
		sub_speed(R_leg.turn_slowdown )
	else if(dir == turn(dir, 135) || dir == turn(dir, -135))
		sub_speed((L_leg.turn_slowdown + L_leg.turn_diogonal_slowdown))
		sub_speed((R_leg.turn_slowdown + R_leg.turn_diogonal_slowdown))
	else if(dir == turn(dir, 180) || dir == turn(dir, -180))
		current_speed = L_leg.min_speed + R_leg.min_speed
	add_heat(L_leg.heat_generation)
	add_heat(R_leg.heat_generation)
	set_dir(moving_dir)
	SetMoveCooldown((L_leg.turn_delay + R_leg.turn_delay)/2)
