#define CULTURE_POSITRONICS_FIRSTGEN   "First Gen - Owned"
#define CULTURE_POSITRONICS_SECONDGEN_OWNED   "Second Gen - Owned"
#define CULTURE_POSITRONICS_SECONDGEN_FREE   "Second Gen - Free Resident"
#define CULTURE_POSITRONICS_SECONDGEN_UNION   "Second Gen - Union Citizen"
#define CULTURE_POSITRONICS_THIRDGEN_PRIVATELY   "Third Gen - Privately Owned"
#define CULTURE_POSITRONICS_THIRDGEN_CORPORATE   "Third Gen - Corporate Owned"
#define CULTURE_POSITRONICS_THIRDGEN_STATE   "Third Gen - State Owned"
