#ifndef MODPACK_ODYSSEY
#define MODPACK_ODYSSEY

#include "_odyssey.dm"
#include "code/_defines.dm"
#include "code/state.dm"
#include "code/helpers.dm"
#include "code/sector_graph.dm"
#include "code/io.dm"
#include "code/save_turfs.dm"
#include "code/save_machinery.dm"
#include "code/save_structures.dm"
#include "code/save_mechs.dm"
#include "code/save_economy.dm"
#include "code/save_newscast.dm"
#include "code/save_shuttles.dm"
#include "code/save_corpses.dm"
#include "code/roster.dm"
#include "code/crew_manifest.dm"
#include "code/persist.dm"
#include "code/sleepers.dm"
#include "code/mercs.dm"
#include "code/hostile_antags.dm"
#include "code/controller.dm"
#include "code/navigation.dm"
#include "code/comm_odyssey.dm"
#include "code/newscast_odyssey.dm"
#include "code/bluespace_drive_odyssey.dm"
#include "code/sector_threats.dm"
#include "code/votes.dm"
#include "code/hooks.dm"
#include "code/admin_panel.dm"
#include "code/unit_tests.dm"

#endif
