#include "hallucinations\_base.dm"
#include "hallucinations\_actors.dm"
#include "hallucinations\_audio.dm"
#include "hallucinations\_visual.dm"
#include "hallucinations\_body.dm"
#include "hallucinations\_station.dm"
