/singleton/species/machine
	default_cultural_info = list(
		TAG_CULTURE = CULTURE_ROOT,
		TAG_HOMEWORLD = HOME_SYSTEM_ROOT,
		TAG_FACTION = FACTION_POSITRONICS
	)
	extended_cultural_info = list(
		TAG_HOMEWORLD = list(
			HOME_SYSTEM_ROOT,
			HOME_SYSTEM_PLUTO
		),
		TAG_FACTION = list(
			FACTION_POSITRONICS,
			FACTION_ZPCI,
			FACTION_PCRC,
			FACTION_SAARE,
			FACTION_DAIS,
			FACTION_HEPHAESTUS,
			FACTION_KMS
		)
	)
