/datum/job/roboticist
	min_skill = list(
			SKILL_COMPUTER		=	SKILL_TRAINED,
			SKILL_DEVICES		=	SKILL_TRAINED,
			SKILL_ANATOMY		=	SKILL_TRAINED,
			SKILL_MEDICAL		=	SKILL_BASIC,
			SKILL_ELECTRICAL	=	SKILL_TRAINED
		)
