#undef VP_DRIVER
#undef VP_INTERIOR

#undef ALL_VEHICLE_POSITIONS

#undef VEHICLE_LOAD_DELAY
#undef VEHICLE_ITEM_LOAD

#undef ITEM_SIZE_VEHICLE_SMALL
#undef ITEM_SIZE_VEHICLE
#undef ITEM_SIZE_VEHICLE_LARGE

#undef BASE_VEHICLE_DEATH_EXPLODE_DAMAGE
