name: Проверка Ченджлога

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request_target:
    types: [opened, reopened, edited, labeled, unlabeled]

jobs:
  CheckCL:
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' && github.base_ref == 'dev220' && github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          fetch-depth: 25
      - name: Установка Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: '3.x'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Создание чейнджлога
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python tools/changelog/sierra_check_changelog.py
