name: 'Close stale issues and PRs'

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write # required to close stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'В этом ишью ничего не происходило ничего в течение 30 дней и он будет закрыт через 5 дней, если обновлений не произойдёт.'
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-issue-labels: 'Runtime Error'
