name: "Чейнджлог: PR -> YML"

permissions:
  contents: read

on:
  push:
    branches:
    - dev220

jobs:
  MakeCL:
    permissions:
      contents: write # required to push the changelog chunk yml commit
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 25
      - name: Установка Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: '3.x'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Создание чейнджлога
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_NAME }}"
        run: python tools/changelog/sierra_generate_cl.py
