name: "Чейнджлог: PR -> YML"

permissions:
  contents: read

on:
  push:
    branches:
    - dev220

jobs:
  MakeCL:
    permissions:
      contents: write # required to push the changelog chunk yml commit
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 25
      - name: Установка Python
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
        with:
          python-version: '3.x'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Создание чейнджлога
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_NAME }}"
        run: python tools/changelog/sierra_generate_cl.py
